### ISSUE TITLE
Provide instructions on how to use Docker image

### ISSUE THREAD

**Issue by tddmonkey** [unbounce/yopa#2]
Hey,

It would be useful if you could provide some information on how your Docker image could be used to run Yopa locally.  At the moment running the image results in the following:

```
$ docker run unbounce/yopa

[main] 2015-10-19 13:50:05,820 INFO  [com.unbounce.yopa.core] YOPA is Your Own Personal AWS

Usage: lein run [options]

Options:
  -c, --config CONFIG_FILE                                  YAML configuration file
  -o, --output REGIONS_FILE  /tmp/aws-regions-override.xml  XML regions override file for the Java AWS SDK
  -h, --help

Please refer to the manual page for more information.

YOPA 1.0.0-SNAPSHOT - built on: Tue Jun 30 14:27:37 PDT 2015
```

So out of the box this doesn't provide useful functionality, is there a way to provide the necessary configuration?

Thanks.

**Comment by p4tin** [comment]
- Create a config file in config/yopa.yaml, like this:

```
region: yopa-local
host: localhost
bind-address: 0.0.0.0
sqs:
  port: 47195
sns:
  port: 47196
  https: false
s3:
  port: 47197
  https: false
  data-dir: /tmp/yopa-fake-s3/


messaging:
  - sns://test-topic-with-subscriptions:

    - sqs://test-subscribed-queue-standard

    - { endpoint: "sqs://test-subscribed-queue-raw", rawDelivery: true }

    - http://localhost:47196/request-logger

  - sns://test-topic-without-subscription

  - sqs://test-standalone-queue

storage:
  buckets:
    - test-bucket
    - NOT-DNS-HAPPY-NAME
```
- Create a Dockerfile like this:

```
FROM unbounce/yopa

EXPOSE 47195
EXPOSE 47196
EXPOSE 47197

ADD ./config /config
CMD java -Xms64m -Xmx256m -jar uberjar.jar -c /config/yopa.yaml
```
- build your new image

```
docker build .
```
- The start docker with the command:

```
docker run --name yopa -v config:/config -p 47195:47197 <new name for image you just created in step 2>
```
